# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
        environment:
        - PG_HOST=localhost
        - PG_USER=ubuntu
      - image: circleci/postgres:9.6
        environment:
        - POSTGRES_USER=ubuntu

    working_directory: ~/ft-api

    steps:
      - checkout

      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: pyodbc dependency
          command: |
            sudo apt-get install software-properties-common python-software-properties
            sudo apt-get update
            sudo apt-get install python3-dev unixodbc unixodbc-dev unixodbc-bin tdsodbc libstdc++6 libffi-dev libgss3 freetds-dev

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: setup postgres users
          command: |
            sudo apt update
            sudo apt install postgresql-client
            sudo -u root psql -p 5432 -h 127.0.0.1 -U postgres -c "CREATE USER ft WITH PASSWORD 'test1234';"
            sudo -u root psql -p 5432 -h 127.0.0.1 -U postgres -c "ALTER USER ft WITH superuser;"

      - run:
          name: run tests
          command: |
            mkdir xunit
            . venv/bin/activate
            python manage.py test --with-xunit --xunit-file=./xunit/xunit.xml

      - store_test_results:
          path: ./xunit

      - store_artifacts:
          path: ./xunit
