# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-25 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiEndpoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'api_endpoint',
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('access_key', models.CharField(max_length=128)),
                ('secret_access_key', models.CharField(max_length=128)),
                ('updated', models.DateTimeField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'api_key',
            },
        ),
        migrations.CreateModel(
            name='ApiPermission',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('methods', models.CharField(blank=True, max_length=32, null=True)),
                ('api_endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_permissions', to='ft_api.ApiEndpoint')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_permissions', to='ft_api.ApiKey')),
            ],
            options={
                'db_table': 'api_permission',
            },
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=80)),
                ('auth_type', models.CharField(max_length=150, null=True)),
                ('updated', models.DateTimeField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'auth_token',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=80, null=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('salt', models.CharField(max_length=50, null=True)),
                ('password_reset_token', models.CharField(max_length=50, null=True)),
                ('password_reset_token_created', models.DateTimeField(null=True)),
                ('password_reset_ip', models.GenericIPAddressField(null=True)),
                ('failed_login_attempts', models.IntegerField(default=0, null=True)),
                ('last_failed_login', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='authtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='ft_api.User'),
        ),
    ]
