# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-26 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ft_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('access_key', models.CharField(max_length=150)),
                ('secret_access_key', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.AlterField(
            model_name='apikey',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apipermission',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='ft_api.Application'),
        ),
        migrations.AlterField(
            model_name='apipermission',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
