# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-26 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ft_api', '0006_populate_user_and_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessplan',
            name='fitness_plan_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fitness_plan', to='ft_api.FitnessPlanType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fitnessplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_plan', to='ft_api.User'),
        ),
    ]
